name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ x86_64-unknown-linux-gnu ]
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      run: rustup update stable
    - name: Install cross-compilation tools
      uses: taiki-e/setup-cross-toolchain-action@v1
      with:
        target: x64-unknown-linux-gnu
        
    - name: Install pkg-config and openssl
      run: sudo apt install pkg-config libssl-dev
    - name : cargo update
      run: cargo update
      
    - name: Build
      run: cargo build --release --verbose 
    - name: Run tests
      run: cargo test --verbose

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        path: target/x86_64-unknown-linux-gnu/release/GJ_StampTour
